### ISSUE TITLE
Footer

### ISSUE THREAD

**Issue by castromaciel** [G3-R-Avanzado/Frontend-Native#4]
## Proceso

1. Iniciar sesión
2. Ir hacia el footer

## Resultado esperado

Se espera que el footer se visualice en su totalidad

## Resultado actual

No se visualiza el apartado de otras tarjetas

## Captura

https://github.com/G3-R-Avanzado/Frontend-Native/assets/83432755/897e67a7-5ba1-444a-ab07-a7f1babd4b6b

## Notas

> Cualquier duda/consulta pueden contactarme vía mail, o por canal de slack de la comunidad de Rolling.

**Comment by MauricioSor** [comment]
Buenas @castromaciel ! Solucionamos el bug 🤓
