### ISSUE TITLE
Registro de usuario

### ISSUE THREAD

**Issue by castromaciel** [G3-R-Avanzado/Frontend-Native#5]
## Proceso

1. Ir a registro
2. Diligenciar los campos
3. Dar click en registrar

## Resultado esperado

Se espera poder registrar un usuario. Caso contrario, si el servicio muestra algún error este debe ser presentado al usuario

## Resultado actual

No se crea al usuario, y tampoco se informa el motivo de la no creación

## Captura

![simulator_screenshot_0F26E3B5-1C66-49D9-9A38-0CC0029A3BB9](https://github.com/G3-R-Avanzado/Frontend-Native/assets/83432755/15297f8c-387e-43ef-a6a8-246ee0c63fcc)

Se revisa en los logs y se visualiza el mensaje desde la API

<img width="1366" alt="image" src="https://github.com/G3-R-Avanzado/Frontend-Native/assets/83432755/3b0c5031-89f8-4afd-9bb3-6ec299fe3216">

Sucede con todos los campos.

## Notas

> Cualquier duda/consulta pueden contactarme vía mail, o por canal de slack de la comunidad de Rolling.

**Comment by MauricioSor** [comment]
Hola @castromaciel ! Bug solucionado 🤓
