### ISSUE TITLE
Boton al final de la aplicación

### ISSUE THREAD

**Issue by castromaciel** [G3-R-Avanzado/Frontend-Native#6]
## Proceso

1. Al ingresar a las pantallas de "Mi cuenta", "Registrar",  

## Resultado esperado

Se espera visualizar el botón por completo

## Resultado actual

El mismo se muestra cortado

## Captura

<img width="270" height="580" src="https://github.com/G3-R-Avanzado/Frontend-Native/assets/83432755/6536e9b6-c808-4bcd-8184-f673986831fd" />

<img width="270" height="580" src="https://github.com/G3-R-Avanzado/Frontend-Native/assets/83432755/eec8e9a8-6609-4b5f-a7ae-f61f1edb4723" />

<br />
<br />
<br />

<img width="363" alt="image" src="https://github.com/G3-R-Avanzado/Frontend-Native/assets/83432755/0072d83c-cdda-4696-abc1-0d0eaa2c446b">

## Notas

> Cualquier duda/consulta pueden contactarme vía mail, o por canal de slack de la comunidad de Rolling.

**Comment by MauricioSor** [comment]
Buenas @castromaciel ! Bug fixeado! 👯
