### ISSUE TITLE
Alert not defined

### ISSUE THREAD

**Issue by castromaciel** [G3-R-Avanzado/Frontend-Native#7]
## Proceso

1. Ir al detalle de un producto

## Resultado esperado

Se espera que los botones tengan algun tipo de acción

## Resultado actual

Genera un error al dar click en guardar en una lista

## Captura

<img width="270" height="580" src="https://github.com/G3-R-Avanzado/Frontend-Native/assets/83432755/3f2bb168-a165-420c-bc11-0f2af69ed241" />

<img width="270" height="580" src="https://github.com/G3-R-Avanzado/Frontend-Native/assets/83432755/f0189f73-ca5a-456c-ad4d-962cc96a7585" />

## Notas

> Cualquier duda/consulta pueden contactarme vía mail, o por canal de slack de la comunidad de Rolling.

**Comment by MauricioSor** [comment]
Buenas @castromaciel ! Bug Fixeado 👍🏻
