### ISSUE TITLE
Detalle de producto

### ISSUE THREAD

**Issue by castromaciel** [G3-R-Avanzado/Frontend-Native#8]
#### Detalle de producto

- El titulo está en inglés (DetailProduct)
- No carga la imagen
- no hay espaciados entre los bordes de la pantalla y el contenido

![simulator_screenshot_4615809D-48E4-43B3-B527-F476228675D4](https://github.com/G3-R-Avanzado/Frontend-Native/assets/83432755/ef459f78-bd79-4a17-8790-f57d615944ef)

## Notas

> Cualquier duda/consulta pueden contactarme vía mail, o por canal de slack de la comunidad de Rolling.

**Comment by MauricioSor** [comment]
Buenas tardes, @castromaciel !. Bug Fixeado! Cualquier cosa nos avisas
